spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to SBank loans related prod APIs "
  contactDetails:
    name: "Developer"
    email: "developer@gmail.com"
  onCallSupport:
    - (231) 435-6655
    - (543) 655-5544