spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to SBank accounts related prod APIs "
  contactDetails:
    name: "Developer"
    email: "developer@gmail.com"
  onCallSupport:
    - (123) 456-8674
    - (234) 212-9873